// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NutriCost.Api.Persistence;

#nullable disable

namespace NutriCost.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260923142852_AddUpdatedAtConcurrencyStamp")]
    partial class AddUpdatedAtConcurrencyStamp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NutriCost.Api.Persistence.ExportTemplateEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Preview")
                        .HasColumnType("text")
                        .HasColumnName("preview");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("export_templates", (string)null);
                });

            modelBuilder.Entity("NutriCost.Api.Persistence.IngredientEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.PrimitiveCollection<List<string>>("Allergens")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("allergens");

                    b.PrimitiveCollection<List<string>>("AltCodes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("alt_codes");

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean")
                        .HasColumnName("approved");

                    b.Property<decimal>("Carb")
                        .HasColumnType("numeric")
                        .HasColumnName("carb");

                    b.Property<string>("Cat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cat");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("CodeB")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_b");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric")
                        .HasColumnName("cost");

                    b.Property<string>("CostUom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cost_uom");

                    b.Property<string>("Created")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created");

                    b.Property<decimal>("Density")
                        .HasColumnType("numeric")
                        .HasColumnName("density");

                    b.PrimitiveCollection<List<string>>("DescriptionTags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("description_tags");

                    b.Property<decimal>("Fat")
                        .HasColumnType("numeric")
                        .HasColumnName("fat");

                    b.Property<decimal>("Fibre")
                        .HasColumnType("numeric")
                        .HasColumnName("fibre");

                    b.Property<bool>("Fvn")
                        .HasColumnType("boolean")
                        .HasColumnName("fvn");

                    b.Property<decimal>("Kcal")
                        .HasColumnType("numeric")
                        .HasColumnName("kcal");

                    b.Property<decimal>("Kj")
                        .HasColumnType("numeric")
                        .HasColumnName("kj");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Protein")
                        .HasColumnType("numeric")
                        .HasColumnName("protein");

                    b.Property<decimal>("Salt")
                        .HasColumnType("numeric")
                        .HasColumnName("salt");

                    b.Property<decimal>("Sat")
                        .HasColumnType("numeric")
                        .HasColumnName("sat");

                    b.Property<decimal>("Sugar")
                        .HasColumnType("numeric")
                        .HasColumnName("sugar");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supplier");

                    b.Property<decimal>("UnitWeightG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("unit_weight_g");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.PrimitiveCollection<List<string>>("VersionHistory")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("version_history");

                    b.HasKey("Id");

                    b.ToTable("ingredients", (string)null);
                });

            modelBuilder.Entity("NutriCost.Api.Persistence.IngredientVersionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("IngredientId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ingredient_id");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("snapshot");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId", "VersionNumber");

                    b.ToTable("ingredient_versions", (string)null);
                });

            modelBuilder.Entity("NutriCost.Api.Persistence.RecipeEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean")
                        .HasColumnName("approved");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Created")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("desc");

                    b.PrimitiveCollection<List<string>>("DescriptionTags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("description_tags");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("OwnCost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("own_cost");

                    b.Property<string>("RecipeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipe_type");

                    b.Property<decimal>("Serving")
                        .HasColumnType("numeric")
                        .HasColumnName("serving");

                    b.Property<decimal>("SheetCost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("sheet_cost");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<decimal>("UnitWeightG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("unit_weight_g");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("serving_uom");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.PrimitiveCollection<List<string>>("VersionHistory")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("version_history");

                    b.Property<decimal>("YieldPct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(100m)
                        .HasColumnName("yield_pct");

                    b.HasKey("Id");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("NutriCost.Api.Persistence.RecipeLineEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("FvnOverride")
                        .HasColumnType("numeric")
                        .HasColumnName("fvn_override");

                    b.Property<string>("IngredientId")
                        .HasColumnType("text")
                        .HasColumnName("ingredient_id");

                    b.Property<decimal>("Qty")
                        .HasColumnType("numeric")
                        .HasColumnName("qty");

                    b.Property<string>("RecipeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipe_id");

                    b.Property<decimal>("ScrapPct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("scrap_pct");

                    b.Property<string>("SubRecipeId")
                        .HasColumnType("text")
                        .HasColumnName("sub_recipe_id");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uom");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("SubRecipeId");

                    b.ToTable("recipe_lines", (string)null);
                });

            modelBuilder.Entity("NutriCost.Api.Persistence.RecipeLineEntity", b =>
                {
                    b.HasOne("NutriCost.Api.Persistence.RecipeEntity", "Recipe")
                        .WithMany("Lines")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("NutriCost.Api.Persistence.RecipeEntity", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
